version: "3"
services:
  frontend:
    container_name: react
    build: frontend
    command: ["npm", "start"]
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - nginx_frontend_network

  backend:
    container_name: backend
    ports:
      - "5000:80"
    build: backend
    restart: always
    environment:
      - FLASK_ENV=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    networks:
      - nginx_backend_network
      - backend_network

  db:
    container_name: mhaDb
    image: postgres
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - userdatabase:/var/lib/postgresql/data
    networks:
      - backend_network

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx_frontend_network
      - nginx_backend_network

volumes:
  userdatabase:

networks:
  nginx_frontend_network:
  nginx_backend_network:
  backend_network:
