version: "3"

services:
  frontend:
    build: frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: backend
    ports:
      - 5000:5000
    build: backend
    restart: always
    environment:
      - FLASK_ENV=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

volumes:
  node-modules:
  db:
