name: Docker build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main/master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    name: Run Docker build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build
        run: |
          docker build ./backend && docker build ./frontend

      - name: Start Containers
        run: docker-compose up
