name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
      - uses: actions/checkout@v1

      - name: Set up Eslint
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: frontend/
