name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main/master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    eslint_dir: frontend/
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
